ZO_CreateStringId("SI_SHOPPING_LIST_TITLE", "Shopping List")
ZO_CreateStringId("SI_BINDING_NAME_SHOPPING_LIST_TOGGLE", "Toggle Shopping List")
ZO_CreateStringId("SI_SHOPPING_LIST_DEFAULT_LIST_NAME", "Shopping List")
ZO_CreateStringId("SI_SHOPPING_LIST_DEFAULT_LIST_NUMBERED", "Shopping List <<1>>")
ZO_CreateStringId("SI_SHOPPING_LIST_RESTORED_LIST_NAME", "<<1>> Restored")
ZO_CreateStringId("SI_SHOPPING_LIST_COPIED_LIST_NAME", "<<1>> Copy")

ZO_CreateStringId("SI_SHOPPING_LIST_BUTTON_CLOSE", "Close")
ZO_CreateStringId("SI_SHOPPING_LIST_BUTTON_SAVE", "Save")
ZO_CreateStringId("SI_SHOPPING_LIST_BUTTON_CANCEL", "Cancel")
ZO_CreateStringId("SI_SHOPPING_LIST_BUTTON_CREATE", "Create")
ZO_CreateStringId("SI_SHOPPING_LIST_BUTTON_DELETE", "Delete")
ZO_CreateStringId("SI_SHOPPING_LIST_BUTTON_RENAME", "Rename")
ZO_CreateStringId("SI_SHOPPING_LIST_BUTTON_DUPLICATE", "Duplicate")
ZO_CreateStringId("SI_SHOPPING_LIST_BUTTON_MOVE_UP", "Move Up")
ZO_CreateStringId("SI_SHOPPING_LIST_BUTTON_MOVE_DOWN", "Move Down")
ZO_CreateStringId("SI_SHOPPING_LIST_BUTTON_ARCHIVE", "Archive")
ZO_CreateStringId("SI_SHOPPING_LIST_BUTTON_SHARE", "Share/Import")
ZO_CreateStringId("SI_SHOPPING_LIST_BUTTON_CLEAR", "Clear")
ZO_CreateStringId("SI_SHOPPING_LIST_BUTTON_FIND", "Find")
ZO_CreateStringId("SI_SHOPPING_LIST_BUTTON_RESTORE", "Restore")
ZO_CreateStringId("SI_SHOPPING_LIST_BUTTON_NEWER", "Newer")
ZO_CreateStringId("SI_SHOPPING_LIST_BUTTON_OLDER", "Older")
ZO_CreateStringId("SI_SHOPPING_LIST_BUTTON_HISTORY", "History")
ZO_CreateStringId("SI_SHOPPING_LIST_BUTTON_ADD", "Add")
ZO_CreateStringId("SI_SHOPPING_LIST_BUTTON_EDIT", "Edit")
ZO_CreateStringId("SI_SHOPPING_LIST_BUTTON_BUDGET", "Budget")
ZO_CreateStringId("SI_SHOPPING_LIST_BUTTON_REMOVE", "Remove")
ZO_CreateStringId("SI_SHOPPING_LIST_BUTTON_DONATE", "Donate")

ZO_CreateStringId("SI_SHOPPING_LIST_NOUN_ITEM", "item")
ZO_CreateStringId("SI_SHOPPING_LIST_NOUN_ITEMS", "items")
ZO_CreateStringId("SI_SHOPPING_LIST_NOUN_PURCHASE", "purchase")
ZO_CreateStringId("SI_SHOPPING_LIST_NOUN_PURCHASES", "purchases")
ZO_CreateStringId("SI_SHOPPING_LIST_NOUN_ARCHIVED_LIST", "archived list")
ZO_CreateStringId("SI_SHOPPING_LIST_NOUN_ARCHIVED_LISTS", "archived lists")
ZO_CreateStringId("SI_SHOPPING_LIST_GOLD_SHORT", "<<1>>g")
ZO_CreateStringId("SI_SHOPPING_LIST_GOLD_LONG", "gold")
ZO_CreateStringId("SI_SHOPPING_LIST_GOLD_THOUSANDS", "<<1>>k")
ZO_CreateStringId("SI_SHOPPING_LIST_GOLD_MILLIONS", "<<1>>m")

ZO_CreateStringId("SI_SHOPPING_LIST_ERROR_ENTER_LIST_NAME", "Enter a list name.")
ZO_CreateStringId("SI_SHOPPING_LIST_ERROR_LIST_NAME_EXISTS", "A list with that name already exists.")
ZO_CreateStringId("SI_SHOPPING_LIST_ERROR_SHARED_LIST_NO_NAME", "The shared list has no name.")
ZO_CreateStringId("SI_SHOPPING_LIST_ERROR_SHARED_LIST_NO_ITEMS", "The shared list has no items.")
ZO_CreateStringId("SI_SHOPPING_LIST_ERROR_SHARED_LIST_TOO_MANY_ITEMS", "The shared list contains too many items.")
ZO_CreateStringId("SI_SHOPPING_LIST_ERROR_SHARED_LIST_INVALID_ITEM", "The shared list contains an invalid item.")
ZO_CreateStringId("SI_SHOPPING_LIST_ERROR_LIST_MISSING", "That list no longer exists.")
ZO_CreateStringId("SI_SHOPPING_LIST_ERROR_LIST_REQUIRED", "At least one shopping list is required.")
ZO_CreateStringId("SI_SHOPPING_LIST_ERROR_ARCHIVED_LIST_MISSING", "That archived list no longer exists.")
ZO_CreateStringId("SI_SHOPPING_LIST_ERROR_ENTER_ITEM_NAME", "Enter an item name.")
ZO_CreateStringId("SI_SHOPPING_LIST_ERROR_ITEM_MISSING", "That item is no longer on the list.")
ZO_CreateStringId("SI_SHOPPING_LIST_REMOVE_ITEM_TITLE", "Remove Shopping List Item")
ZO_CreateStringId("SI_SHOPPING_LIST_REMOVE_ITEM_CONFIRM", "Remove <<1>> from this list?")
ZO_CreateStringId("SI_SHOPPING_LIST_STATUS_REMOVED_ITEM", "Removed <<1>>.")
ZO_CreateStringId("SI_SHOPPING_LIST_UNKNOWN_SERVER", "Unknown")
ZO_CreateStringId("SI_SHOPPING_LIST_DONATE_TOOLTIP", "Open a mail to @Gravvy on the NA Megaserver. Nothing is sent automatically.")
ZO_CreateStringId("SI_SHOPPING_LIST_DONATE_WRONG_SERVER", "Donations by mail are only available on NA Megaserver. Current server: <<1>>.")
ZO_CreateStringId("SI_SHOPPING_LIST_DONATE_MAIL_UNAVAILABLE", "ESO's mail composer is not available right now.")

ZO_CreateStringId("SI_SHOPPING_LIST_BUDGET_TOOLTIP", "Open budget settings for this list.")
ZO_CreateStringId("SI_SHOPPING_LIST_ITEM_NAME_PLACEHOLDER", "Item name")
ZO_CreateStringId("SI_SHOPPING_LIST_ORDER", "Order")
ZO_CreateStringId("SI_SHOPPING_LIST_ARCHIVED_COUNT", "Archived (<<1>>)")
ZO_CreateStringId("SI_SHOPPING_LIST_STATUS_LIST_ORDER_UPDATED", "List order updated.")
ZO_CreateStringId("SI_SHOPPING_LIST_STATUS_LIST_ARCHIVED", "Archived <<1>>.")
ZO_CreateStringId("SI_SHOPPING_LIST_BUDGET_TITLE", "List Budget")
ZO_CreateStringId("SI_SHOPPING_LIST_NO_BUDGET", "No budget")
ZO_CreateStringId("SI_SHOPPING_LIST_RECORDED_SPENDING", "Recorded spending: <<1>>")
ZO_CreateStringId("SI_SHOPPING_LIST_STATUS_BUDGET_UPDATED", "List budget updated.")
ZO_CreateStringId("SI_SHOPPING_LIST_STATUS_BUDGET_CLEARED", "List budget cleared.")
ZO_CreateStringId("SI_SHOPPING_LIST_NEW_LIST_TITLE", "New Shopping List")
ZO_CreateStringId("SI_SHOPPING_LIST_RENAME_LIST_TITLE", "Rename Shopping List")
ZO_CreateStringId("SI_SHOPPING_LIST_DUPLICATE_LIST_TITLE", "Duplicate Shopping List")
ZO_CreateStringId("SI_SHOPPING_LIST_DELETE_LIST_TITLE", "Delete Shopping List")
ZO_CreateStringId("SI_SHOPPING_LIST_DELETE_LIST_CONFIRM", "Delete \"<<1>>\" and all of its items?")
ZO_CreateStringId("SI_SHOPPING_LIST_STATUS_LISTS_UPDATED", "Shopping lists updated.")
ZO_CreateStringId("SI_SHOPPING_LIST_PAGE_WITH_HINT", "<<1>>–<<2>> of <<3>> · <<4>>")
ZO_CreateStringId("SI_SHOPPING_LIST_HINT_SCROLL", "scroll")
ZO_CreateStringId("SI_SHOPPING_LIST_HINT_MOUSE_WHEEL", "mouse wheel")
ZO_CreateStringId("SI_SHOPPING_LIST_STATUS_ADDED_ITEM", "Added <<1>>.")
ZO_CreateStringId("SI_SHOPPING_LIST_SUMMARY_WITH_BUDGET", "<<1>>/<<2>> · <<3>>/<<4>>")
ZO_CreateStringId("SI_SHOPPING_LIST_SUMMARY_SPENT", "<<1>>/<<2>> · <<3>> spent")
ZO_CreateStringId("SI_SHOPPING_LIST_PAGE", "<<1>>–<<2>> of <<3>>")
ZO_CreateStringId("SI_SHOPPING_LIST_SEARCH_TARGET", "Target: <<1>> each.")
ZO_CreateStringId("SI_SHOPPING_LIST_STATUS_WINDOW_RESET", "Window position and size reset.")
ZO_CreateStringId("SI_SHOPPING_LIST_GAMEPAD_EMPTY", "This list has no items.")
ZO_CreateStringId("SI_SHOPPING_LIST_GAMEPAD_MARK_COMPLETE", "Mark Complete")
ZO_CreateStringId("SI_SHOPPING_LIST_GAMEPAD_MARK_INCOMPLETE", "Mark Incomplete")
ZO_CreateStringId("SI_SHOPPING_LIST_GAMEPAD_REMOVE_ITEM", "Remove Item")
ZO_CreateStringId("SI_SHOPPING_LIST_GAMEPAD_REMOVE_CONFIRM", "Remove <<1>> from this list?")
ZO_CreateStringId("SI_SHOPPING_LIST_GAMEPAD_REMOVED_ITEM", "Removed <<1>>.")
ZO_CreateStringId("SI_SHOPPING_LIST_GAMEPAD_PREVIOUS_LIST", "Previous List")
ZO_CreateStringId("SI_SHOPPING_LIST_GAMEPAD_NEXT_LIST", "Next List")
ZO_CreateStringId("SI_SHOPPING_LIST_GAMEPAD_ITEM_PROGRESS", "<<1>> / <<2>> purchased")
ZO_CreateStringId("SI_SHOPPING_LIST_GAMEPAD_PRICE_TARGET", "Target: <<1>> each")
ZO_CreateStringId("SI_SHOPPING_LIST_GAMEPAD_ADD_ITEM", "Add Item")
ZO_CreateStringId("SI_SHOPPING_LIST_GAMEPAD_ADD_ITEM_TITLE", "Add Shopping List Item")
ZO_CreateStringId("SI_SHOPPING_LIST_GAMEPAD_ITEM_NAME", "Item name")
ZO_CreateStringId("SI_SHOPPING_LIST_GAMEPAD_QUANTITY", "Quantity")
ZO_CreateStringId("SI_SHOPPING_LIST_GAMEPAD_MANAGE", "Manage")
ZO_CreateStringId("SI_SHOPPING_LIST_GAMEPAD_MANAGE_TITLE", "Manage Shopping List")
ZO_CreateStringId("SI_SHOPPING_LIST_GAMEPAD_MANAGE_HELP", "Edit the selected item or manage this list's archive and sharing options.")
ZO_CreateStringId("SI_SHOPPING_LIST_GAMEPAD_EDIT_MATCHING", "Edit Matching Rules")
ZO_CreateStringId("SI_SHOPPING_LIST_GAMEPAD_ARCHIVE_CURRENT", "Archive Current List")
ZO_CreateStringId("SI_SHOPPING_LIST_GAMEPAD_SHARE_CURRENT", "Share Current List")
ZO_CreateStringId("SI_SHOPPING_LIST_GAMEPAD_IMPORT_LIST", "Import List")
ZO_CreateStringId("SI_SHOPPING_LIST_GAMEPAD_QUALITY", "Quality")
ZO_CreateStringId("SI_SHOPPING_LIST_GAMEPAD_ARCHIVE_DETAILS", "<<1>> entries · <<2>> spent")
ZO_CreateStringId("SI_SHOPPING_LIST_GAMEPAD_SHARE_HELP", "Select the code field, then use Ctrl+C on the keyboard to copy it.")
ZO_CreateStringId("SI_SHOPPING_LIST_GAMEPAD_IMPORT_HELP", "Select the field, then paste a Shopping List code with Ctrl+V or the on-screen keyboard.")
ZO_CreateStringId("SI_SHOPPING_LIST_GAMEPAD_HELP", "Help & Release Notes")

ZO_CreateStringId("SI_SHOPPING_LIST_HELP_TITLE", "Shopping List Help")
ZO_CreateStringId("SI_SHOPPING_LIST_HELP_GETTING_STARTED", "Getting Started")
ZO_CreateStringId("SI_SHOPPING_LIST_HELP_RELEASE_NOTES", "Release Notes")
ZO_CreateStringId("SI_SHOPPING_LIST_HELP_TOOLTIP", "Open help and release notes.")
ZO_CreateStringId("SI_SHOPPING_LIST_HELP_CONTENT", "Shopping List tracks purchases from the guild store currently open. It never searches traders remotely.\n\n1. Create or select a named list.\n2. Enter an item name and quantity.\n3. Use Edit to set matching rules or a price target.\n4. Open a guild store and use Find.\n5. Successful purchases update the current list automatically.\n\nBudget tracks spending without blocking a purchase.\nShare/Import codes contain only the list name, item names, and quantities.\nArchive stores lists until you restore them.\n\nUse /shoppinglist to toggle the window.\nUse /shoppinglisthelp to reopen this panel.\nIn gamepad mode, press the right stick for Manage and Help.")
ZO_CreateStringId("SI_SHOPPING_LIST_RELEASE_NOTES_CONTENT", "0.15.1\n• Lists can now be archived whether they are unfinished, completed, or empty.\n• Corrected the Archive button appearing unresponsive for unfinished lists.\n\n0.15.0\n• Added in-game help and recent release notes for keyboard and gamepad.\n• Added the /shoppinglisthelp command and a ? button in the main window.\n\n0.14.0\n• Added the gamepad Manage menu.\n• Added controller editing for matching rules and price targets.\n• Added controller archive, restore, share, and import workflows.\n\n0.13.6\n• Corrected Import dialog layering above the Share window.\n\n0.13.5\n• Added the optional NA-only in-game donation-mail shortcut.\n\n0.13.4\n• Added a dedicated import paste dialog and item-removal confirmation.")

ZO_CreateStringId("SI_SHOPPING_LIST_ARCHIVE_TITLE", "Archived Shopping Lists")
ZO_CreateStringId("SI_SHOPPING_LIST_ARCHIVE_EMPTY", "No shopping lists have been archived.")
ZO_CreateStringId("SI_SHOPPING_LIST_ARCHIVE_COLUMN_LIST", "List")
ZO_CreateStringId("SI_SHOPPING_LIST_ARCHIVE_COLUMN_DETAILS", "Archived / Spending")
ZO_CreateStringId("SI_SHOPPING_LIST_STATUS_LIST_RESTORED", "Restored <<1>>.")
ZO_CreateStringId("SI_SHOPPING_LIST_ARCHIVE_SUMMARY", "<<1>> <<2>>")
ZO_CreateStringId("SI_SHOPPING_LIST_ARCHIVE_ROW", "<<1>>  (<<2>> <<3>>)")
ZO_CreateStringId("SI_SHOPPING_LIST_ARCHIVE_DETAILS", "<<1>> · <<2>>")

ZO_CreateStringId("SI_SHOPPING_LIST_HISTORY_TITLE", "Purchase History")
ZO_CreateStringId("SI_SHOPPING_LIST_HISTORY_DATE", "Date")
ZO_CreateStringId("SI_SHOPPING_LIST_HISTORY_QUANTITY", "Qty")
ZO_CreateStringId("SI_SHOPPING_LIST_HISTORY_EACH", "Each")
ZO_CreateStringId("SI_SHOPPING_LIST_HISTORY_TOTAL", "Total")
ZO_CreateStringId("SI_SHOPPING_LIST_HISTORY_SOURCE", "Guild / Seller")
ZO_CreateStringId("SI_SHOPPING_LIST_UNKNOWN_DATE", "Unknown")
ZO_CreateStringId("SI_SHOPPING_LIST_UNKNOWN_TRADER", "Unknown trader")
ZO_CreateStringId("SI_SHOPPING_LIST_HISTORY_SUMMARY", "<<1>> <<2>> · <<3>> total")
ZO_CreateStringId("SI_SHOPPING_LIST_NO_RECORDED_PURCHASES", "No recorded purchases")

ZO_CreateStringId("SI_SHOPPING_LIST_EDITOR_TITLE", "Edit Shopping List Item")
ZO_CreateStringId("SI_SHOPPING_LIST_EDITOR_QUANTITY", "Quantity")
ZO_CreateStringId("SI_SHOPPING_LIST_EDITOR_SET", "Set")
ZO_CreateStringId("SI_SHOPPING_LIST_EDITOR_ANY_SET", "Any set")
ZO_CreateStringId("SI_SHOPPING_LIST_EDITOR_TRAIT", "Trait")
ZO_CreateStringId("SI_SHOPPING_LIST_EDITOR_ANY_TRAIT", "Any trait")
ZO_CreateStringId("SI_SHOPPING_LIST_EDITOR_QUALITY_RULE", "Quality rule")
ZO_CreateStringId("SI_SHOPPING_LIST_EDITOR_LEVEL_RULE", "Level rule")
ZO_CreateStringId("SI_SHOPPING_LIST_EDITOR_LEVEL", "Level")
ZO_CreateStringId("SI_SHOPPING_LIST_EDITOR_CHAMPION_POINTS", "Champion points")
ZO_CreateStringId("SI_SHOPPING_LIST_EDITOR_MAX_UNIT_PRICE", "Maximum unit price")
ZO_CreateStringId("SI_SHOPPING_LIST_EDITOR_GOLD_NONE", "gold (blank = none)")
ZO_CreateStringId("SI_SHOPPING_LIST_EDITOR_HINT", "Any leaves that property unrestricted. Set names must match exactly.")
ZO_CreateStringId("SI_SHOPPING_LIST_CHOICE_ANY", "Any")
ZO_CreateStringId("SI_SHOPPING_LIST_CHOICE_AT_LEAST", "At least")
ZO_CreateStringId("SI_SHOPPING_LIST_CHOICE_EXACTLY", "Exactly")
ZO_CreateStringId("SI_SHOPPING_LIST_NO_PURCHASE_PRICES", "No purchase prices recorded yet.")
ZO_CreateStringId("SI_SHOPPING_LIST_LAST_UNIT_PRICE", "Last <<1>> each")
ZO_CreateStringId("SI_SHOPPING_LIST_OVER_TARGET", "over target")
ZO_CreateStringId("SI_SHOPPING_LIST_PURCHASE_SUMMARY", "<<1>> <<2>> · <<3>> total · <<4>> average\n<<5>>")
ZO_CreateStringId("SI_SHOPPING_LIST_STATUS_ITEM_ORDER_UPDATED", "Item order updated.")
ZO_CreateStringId("SI_SHOPPING_LIST_STATUS_ITEM_UPDATED", "Updated <<1>>.")

ZO_CreateStringId("SI_SHOPPING_LIST_SHARE_ERROR_NO_LIST", "There is no list to share.")
ZO_CreateStringId("SI_SHOPPING_LIST_SHARE_ERROR_LIST_NAME_LONG", "The list name is too long to share.")
ZO_CreateStringId("SI_SHOPPING_LIST_SHARE_ERROR_TOO_MANY_ITEMS", "Lists with more than 500 items cannot be shared.")
ZO_CreateStringId("SI_SHOPPING_LIST_SHARE_ERROR_ITEM_NAME_LONG", "One of the item names is too long to share.")
ZO_CreateStringId("SI_SHOPPING_LIST_SHARE_ERROR_QUANTITY", "Shared item quantities must be between 1 and 1,000,000.")
ZO_CreateStringId("SI_SHOPPING_LIST_SHARE_ERROR_LIST_LONG", "This list is too large for a sharing code.")
ZO_CreateStringId("SI_SHOPPING_LIST_SHARE_ERROR_CODE_LONG", "That sharing code is too long.")
ZO_CreateStringId("SI_SHOPPING_LIST_SHARE_ERROR_PREFIX", "Shopping List codes must begin with <<1>>")
ZO_CreateStringId("SI_SHOPPING_LIST_SHARE_ERROR_INVALID", "That sharing code is not valid.")
ZO_CreateStringId("SI_SHOPPING_LIST_SHARE_ERROR_VERSION", "This sharing code uses an unsupported format.")
ZO_CreateStringId("SI_SHOPPING_LIST_SHARE_ERROR_LIST_DATA", "That sharing code contains invalid list data.")
ZO_CreateStringId("SI_SHOPPING_LIST_SHARE_ERROR_ITEM_DATA", "That sharing code contains invalid item data.")
ZO_CreateStringId("SI_SHOPPING_LIST_SHARE_ERROR_EXTRA_DATA", "That sharing code contains unexpected data.")
ZO_CreateStringId("SI_SHOPPING_LIST_SHARE_TITLE", "Share Shopping List")
ZO_CreateStringId("SI_SHOPPING_LIST_SHARE_HELP", "To share: copy this list's code and send it to another player.\nTo import: choose Import Code and paste the received code.")
ZO_CreateStringId("SI_SHOPPING_LIST_SHARE_CURRENT_CODE", "Current List Code")
ZO_CreateStringId("SI_SHOPPING_LIST_SHARE_SELECT_CODE", "Select Code")
ZO_CreateStringId("SI_SHOPPING_LIST_SHARE_IMPORT_CODE", "Import Code")
ZO_CreateStringId("SI_SHOPPING_LIST_SHARE_COPY_HINT", "Press Ctrl+C to copy the selected code.")
ZO_CreateStringId("SI_SHOPPING_LIST_STATUS_LIST_IMPORTED", "Imported <<1>> with <<2>> <<3>>.")
ZO_CreateStringId("SI_SHOPPING_LIST_IMPORT_TITLE", "Import Shopping List")
ZO_CreateStringId("SI_SHOPPING_LIST_IMPORT_HELP", "Paste a Shopping List sharing code below.")
ZO_CreateStringId("SI_SHOPPING_LIST_IMPORT_PLACEHOLDER", "Paste sharing code")

ZO_CreateStringId("SI_SHOPPING_LIST_SETTINGS_OPEN_WITH_STORE", "Open with guild stores")
ZO_CreateStringId("SI_SHOPPING_LIST_SETTINGS_CLOSE_WITH_STORE", "Close with guild stores")
ZO_CreateStringId("SI_SHOPPING_LIST_SETTINGS_SHOW_COMPLETED", "Show completed items")
ZO_CreateStringId("SI_SHOPPING_LIST_SETTINGS_ANNOUNCE_PURCHASES", "Announce matched purchases")
ZO_CreateStringId("SI_SHOPPING_LIST_SETTINGS_PANEL_SIDE", "Preferred panel side")
ZO_CreateStringId("SI_SHOPPING_LIST_SETTINGS_LEFT", "Left")
ZO_CreateStringId("SI_SHOPPING_LIST_SETTINGS_RIGHT", "Right")
ZO_CreateStringId("SI_SHOPPING_LIST_SETTINGS_RESET_WINDOW", "Reset window position and size")
ZO_CreateStringId("SI_SHOPPING_LIST_SETTINGS_CLEAR_COMPLETED", "Remove completed items from current list")

ZO_CreateStringId("SI_SHOPPING_LIST_SEARCH_OPEN_STORE", "Open a guild store before searching.")
ZO_CreateStringId("SI_SHOPPING_LIST_SEARCHING_FOR", "Searching for <<1>>.")
ZO_CreateStringId("SI_SHOPPING_LIST_SEARCH_AGS_NOT_READY", "AwesomeGuildStore's search is not ready yet.")
ZO_CreateStringId("SI_SHOPPING_LIST_SEARCH_CHOOSE_AUTOCOMPLETE", "Choose an autocomplete result to make this item searchable.")
ZO_CreateStringId("SI_SHOPPING_LIST_CONTEXT_ADD_TO_LIST", "Add to <<1>>")
ZO_CreateStringId("SI_SHOPPING_LIST_CHAT_OVER_BUDGET", "Shopping List: <<1>> is over budget by <<2>> gold.")
ZO_CreateStringId("SI_SHOPPING_LIST_CHAT_PURCHASE_PROGRESS", "Shopping List: <<1>> <<2>>/<<3>>")
