ZO_CreateStringId("SI_SHOPPING_LIST_TITLE", "Shopping List")
ZO_CreateStringId("SI_BINDING_NAME_SHOPPING_LIST_TOGGLE", "Toggle Shopping List")
ZO_CreateStringId("SI_SHOPPING_LIST_DEFAULT_LIST_NAME", "Shopping List")
ZO_CreateStringId("SI_SHOPPING_LIST_DEFAULT_LIST_NUMBERED", "Shopping List <<1>>")
ZO_CreateStringId("SI_SHOPPING_LIST_RESTORED_LIST_NAME", "<<1>> Restored")
ZO_CreateStringId("SI_SHOPPING_LIST_COPIED_LIST_NAME", "<<1>> Copy")

ZO_CreateStringId("SI_SHOPPING_LIST_BUTTON_CLOSE", "Close")
ZO_CreateStringId("SI_SHOPPING_LIST_BUTTON_SAVE", "Save")
ZO_CreateStringId("SI_SHOPPING_LIST_BUTTON_CANCEL", "Cancel")
ZO_CreateStringId("SI_SHOPPING_LIST_BUTTON_CREATE", "Create")
ZO_CreateStringId("SI_SHOPPING_LIST_BUTTON_DELETE", "Delete")
ZO_CreateStringId("SI_SHOPPING_LIST_BUTTON_RENAME", "Rename")
ZO_CreateStringId("SI_SHOPPING_LIST_BUTTON_DUPLICATE", "Duplicate")
ZO_CreateStringId("SI_SHOPPING_LIST_BUTTON_MOVE_UP", "Move Up")
ZO_CreateStringId("SI_SHOPPING_LIST_BUTTON_MOVE_DOWN", "Move Down")
ZO_CreateStringId("SI_SHOPPING_LIST_BUTTON_ARCHIVE", "Archive")
ZO_CreateStringId("SI_SHOPPING_LIST_BUTTON_SHARE", "Share/Import")
ZO_CreateStringId("SI_SHOPPING_LIST_BUTTON_CLEAR", "Clear")
ZO_CreateStringId("SI_SHOPPING_LIST_BUTTON_FIND", "Find")
ZO_CreateStringId("SI_SHOPPING_LIST_BUTTON_RESTORE", "Restore")
ZO_CreateStringId("SI_SHOPPING_LIST_BUTTON_NEWER", "Newer")
ZO_CreateStringId("SI_SHOPPING_LIST_BUTTON_OLDER", "Older")
ZO_CreateStringId("SI_SHOPPING_LIST_BUTTON_HISTORY", "History")
ZO_CreateStringId("SI_SHOPPING_LIST_BUTTON_ADD", "Add")
ZO_CreateStringId("SI_SHOPPING_LIST_BUTTON_EDIT", "Edit")
ZO_CreateStringId("SI_SHOPPING_LIST_BUTTON_BUDGET", "Budget")
ZO_CreateStringId("SI_SHOPPING_LIST_BUTTON_REMOVE", "Remove")
ZO_CreateStringId("SI_SHOPPING_LIST_BUTTON_DONATE", "Donate")
ZO_CreateStringId("SI_SHOPPING_LIST_BUTTON_TRIP", "Trip")
ZO_CreateStringId("SI_SHOPPING_LIST_BUTTON_BULK_ADD", "Bulk Add")
ZO_CreateStringId("SI_SHOPPING_LIST_BUTTON_UNDO", "Undo")
ZO_CreateStringId("SI_SHOPPING_LIST_BUTTON_CLEAR_COMPLETED", "Clear Completed")

ZO_CreateStringId("SI_SHOPPING_LIST_NOUN_ITEM", "item")
ZO_CreateStringId("SI_SHOPPING_LIST_NOUN_ITEMS", "items")
ZO_CreateStringId("SI_SHOPPING_LIST_NOUN_PURCHASE", "purchase")
ZO_CreateStringId("SI_SHOPPING_LIST_NOUN_PURCHASES", "purchases")
ZO_CreateStringId("SI_SHOPPING_LIST_NOUN_ARCHIVED_LIST", "archived list")
ZO_CreateStringId("SI_SHOPPING_LIST_NOUN_ARCHIVED_LISTS", "archived lists")
ZO_CreateStringId("SI_SHOPPING_LIST_GOLD_SHORT", "<<1>>g")
ZO_CreateStringId("SI_SHOPPING_LIST_GOLD_LONG", "gold")
ZO_CreateStringId("SI_SHOPPING_LIST_GOLD_THOUSANDS", "<<1>>k")
ZO_CreateStringId("SI_SHOPPING_LIST_GOLD_MILLIONS", "<<1>>m")

ZO_CreateStringId("SI_SHOPPING_LIST_ERROR_ENTER_LIST_NAME", "Enter a list name.")
ZO_CreateStringId("SI_SHOPPING_LIST_ERROR_LIST_NAME_EXISTS", "A list with that name already exists.")
ZO_CreateStringId("SI_SHOPPING_LIST_ERROR_SHARED_LIST_NO_NAME", "The shared list has no name.")
ZO_CreateStringId("SI_SHOPPING_LIST_ERROR_SHARED_LIST_NO_ITEMS", "The shared list has no items.")
ZO_CreateStringId("SI_SHOPPING_LIST_ERROR_SHARED_LIST_TOO_MANY_ITEMS", "The shared list contains too many items.")
ZO_CreateStringId("SI_SHOPPING_LIST_ERROR_SHARED_LIST_INVALID_ITEM", "The shared list contains an invalid item.")
ZO_CreateStringId("SI_SHOPPING_LIST_ERROR_LIST_MISSING", "That list no longer exists.")
ZO_CreateStringId("SI_SHOPPING_LIST_ERROR_LIST_REQUIRED", "At least one shopping list is required.")
ZO_CreateStringId("SI_SHOPPING_LIST_ERROR_ARCHIVED_LIST_MISSING", "That archived list no longer exists.")
ZO_CreateStringId("SI_SHOPPING_LIST_ERROR_TRIP_LIST_REQUIRED", "At least one list must remain active for shopping trips.")
ZO_CreateStringId("SI_SHOPPING_LIST_ERROR_NOTHING_TO_UNDO", "There is nothing to undo.")
ZO_CreateStringId("SI_SHOPPING_LIST_ERROR_UNDO_LIST_MISSING", "The list that contained those items is no longer available. Restore the list first, then try Undo again.")
ZO_CreateStringId("SI_SHOPPING_LIST_ERROR_ENTER_ITEM_NAME", "Enter an item name.")
ZO_CreateStringId("SI_SHOPPING_LIST_ERROR_ITEM_MISSING", "That item is no longer on the list.")
ZO_CreateStringId("SI_SHOPPING_LIST_REMOVE_ITEM_TITLE", "Remove Shopping List Item")
ZO_CreateStringId("SI_SHOPPING_LIST_REMOVE_ITEM_CONFIRM", "Remove <<1>> from this list?")
ZO_CreateStringId("SI_SHOPPING_LIST_STATUS_REMOVED_ITEM", "Removed <<1>>. Open Manage to undo.")
ZO_CreateStringId("SI_SHOPPING_LIST_UNKNOWN_SERVER", "Unknown")
ZO_CreateStringId("SI_SHOPPING_LIST_DONATE_TOOLTIP", "Open a mail to @Gravvy on the NA Megaserver. Nothing is sent automatically.")
ZO_CreateStringId("SI_SHOPPING_LIST_DONATE_WRONG_SERVER", "Donations by mail are only available on NA Megaserver. Current server: <<1>>.")
ZO_CreateStringId("SI_SHOPPING_LIST_DONATE_MAIL_UNAVAILABLE", "ESO's mail composer is not available right now.")
ZO_CreateStringId("SI_SHOPPING_LIST_CHAT_MISSING_LIBRARIES", "Shopping List could not load. Missing required libraries: <<1>>.")

ZO_CreateStringId("SI_SHOPPING_LIST_BUDGET_TOOLTIP", "Open budget settings for this list.")
ZO_CreateStringId("SI_SHOPPING_LIST_ITEM_NAME_PLACEHOLDER", "Item name")
ZO_CreateStringId("SI_SHOPPING_LIST_ORDER", "Order")
ZO_CreateStringId("SI_SHOPPING_LIST_ARCHIVED_COUNT", "Archived (<<1>>)")
ZO_CreateStringId("SI_SHOPPING_LIST_STATUS_LIST_ORDER_UPDATED", "List order updated.")
ZO_CreateStringId("SI_SHOPPING_LIST_STATUS_LIST_ARCHIVED", "Archived <<1>>.")
ZO_CreateStringId("SI_SHOPPING_LIST_BUDGET_TITLE", "List Budget")
ZO_CreateStringId("SI_SHOPPING_LIST_NO_BUDGET", "No budget")
ZO_CreateStringId("SI_SHOPPING_LIST_RECORDED_SPENDING", "Recorded spending: <<1>>")
ZO_CreateStringId("SI_SHOPPING_LIST_STATUS_BUDGET_UPDATED", "List budget updated.")
ZO_CreateStringId("SI_SHOPPING_LIST_STATUS_BUDGET_CLEARED", "List budget cleared.")
ZO_CreateStringId("SI_SHOPPING_LIST_NEW_LIST_TITLE", "New Shopping List")
ZO_CreateStringId("SI_SHOPPING_LIST_RENAME_LIST_TITLE", "Rename Shopping List")
ZO_CreateStringId("SI_SHOPPING_LIST_DUPLICATE_LIST_TITLE", "Duplicate Shopping List")
ZO_CreateStringId("SI_SHOPPING_LIST_DELETE_LIST_TITLE", "Delete Shopping List")
ZO_CreateStringId("SI_SHOPPING_LIST_DELETE_LIST_CONFIRM", "Delete \"<<1>>\" and all of its items?")
ZO_CreateStringId("SI_SHOPPING_LIST_STATUS_LISTS_UPDATED", "Shopping lists updated.")
ZO_CreateStringId("SI_SHOPPING_LIST_STATUS_LIST_DELETED", "Deleted <<1>>. Open Manage to undo.")
ZO_CreateStringId("SI_SHOPPING_LIST_STATUS_UNDO_COMPLETE", "Restored the most recently deleted entry.")
ZO_CreateStringId("SI_SHOPPING_LIST_STATUS_NO_COMPLETED_ITEMS", "This list has no completed items to clear.")
ZO_CreateStringId("SI_SHOPPING_LIST_STATUS_CLEARED_COMPLETED", "Cleared <<1>> completed items. Use Undo to restore them.")
ZO_CreateStringId("SI_SHOPPING_LIST_STATUS_FILTER_UPDATED", "Filter: <<1>>.")
ZO_CreateStringId("SI_SHOPPING_LIST_PAGE_WITH_HINT", "<<1>>–<<2>> of <<3>> · <<4>>")
ZO_CreateStringId("SI_SHOPPING_LIST_HINT_SCROLL", "scroll")
ZO_CreateStringId("SI_SHOPPING_LIST_HINT_MOUSE_WHEEL", "mouse wheel")
ZO_CreateStringId("SI_SHOPPING_LIST_STATUS_ADDED_ITEM", "Added <<1>>.")
ZO_CreateStringId("SI_SHOPPING_LIST_SUMMARY_WITH_BUDGET", "<<1>>/<<2>> · <<3>>/<<4>>")
ZO_CreateStringId("SI_SHOPPING_LIST_SUMMARY_SPENT", "<<1>>/<<2>> · <<3>> spent")
ZO_CreateStringId("SI_SHOPPING_LIST_PAGE", "<<1>>–<<2>> of <<3>>")
ZO_CreateStringId("SI_SHOPPING_LIST_SEARCH_TARGET", "Target: <<1>> each.")
ZO_CreateStringId("SI_SHOPPING_LIST_STATUS_WINDOW_RESET", "Window position and size reset.")
ZO_CreateStringId("SI_SHOPPING_LIST_GAMEPAD_EMPTY", "This list has no items.")
ZO_CreateStringId("SI_SHOPPING_LIST_GAMEPAD_MARK_COMPLETE", "Mark Complete")
ZO_CreateStringId("SI_SHOPPING_LIST_GAMEPAD_MARK_INCOMPLETE", "Mark Incomplete")
ZO_CreateStringId("SI_SHOPPING_LIST_GAMEPAD_REMOVE_ITEM", "Remove Item")
ZO_CreateStringId("SI_SHOPPING_LIST_GAMEPAD_REMOVE_CONFIRM", "Remove <<1>> from this list?")
ZO_CreateStringId("SI_SHOPPING_LIST_GAMEPAD_REMOVED_ITEM", "Removed <<1>>. Use Undo in Manage to restore it.")
ZO_CreateStringId("SI_SHOPPING_LIST_GAMEPAD_PREVIOUS_LIST", "Previous List")
ZO_CreateStringId("SI_SHOPPING_LIST_GAMEPAD_NEXT_LIST", "Next List")
ZO_CreateStringId("SI_SHOPPING_LIST_GAMEPAD_ITEM_PROGRESS", "<<1>> / <<2>> purchased")
ZO_CreateStringId("SI_SHOPPING_LIST_GAMEPAD_ITEM_OWNED", "Owned: <<1>> · Backpack <<2>> · Bank <<3>> · Craft Bag <<4>>")
ZO_CreateStringId("SI_SHOPPING_LIST_GAMEPAD_ITEM_NOTE", "Note: <<1>>")
ZO_CreateStringId("SI_SHOPPING_LIST_GAMEPAD_PRICE_TARGET", "Target: <<1>> each")
ZO_CreateStringId("SI_SHOPPING_LIST_GAMEPAD_ADD_ITEM", "Add Item")
ZO_CreateStringId("SI_SHOPPING_LIST_GAMEPAD_ADD_ITEM_TITLE", "Add Shopping List Item")
ZO_CreateStringId("SI_SHOPPING_LIST_GAMEPAD_ITEM_NAME", "Item name")
ZO_CreateStringId("SI_SHOPPING_LIST_GAMEPAD_QUANTITY", "Quantity")
ZO_CreateStringId("SI_SHOPPING_LIST_GAMEPAD_MANAGE", "Manage")
ZO_CreateStringId("SI_SHOPPING_LIST_GAMEPAD_MANAGE_TITLE", "Manage Shopping List")
ZO_CreateStringId("SI_SHOPPING_LIST_GAMEPAD_MANAGE_HELP", "Manage lists, items, shopping trips, archives, and sharing.")
ZO_CreateStringId("SI_SHOPPING_LIST_GAMEPAD_CREATE_LIST", "Create List")
ZO_CreateStringId("SI_SHOPPING_LIST_GAMEPAD_LIST_NAME", "List name")
ZO_CreateStringId("SI_SHOPPING_LIST_GAMEPAD_FILTER", "Filter: <<1>>")
ZO_CreateStringId("SI_SHOPPING_LIST_GAMEPAD_TRIP_HEADING", "<<1>> · Trip across <<2>> lists")
ZO_CreateStringId("SI_SHOPPING_LIST_GAMEPAD_SOURCE_LIST", "List: <<1>>")
ZO_CreateStringId("SI_SHOPPING_LIST_GAMEPAD_EDIT_MATCHING", "Edit Matching Rules")
ZO_CreateStringId("SI_SHOPPING_LIST_GAMEPAD_ARCHIVE_CURRENT", "Archive Current List")
ZO_CreateStringId("SI_SHOPPING_LIST_GAMEPAD_SHARE_CURRENT", "Share Current List")
ZO_CreateStringId("SI_SHOPPING_LIST_GAMEPAD_IMPORT_LIST", "Import List")
ZO_CreateStringId("SI_SHOPPING_LIST_GAMEPAD_BACKUP", "Full Backup / Restore")
ZO_CreateStringId("SI_SHOPPING_LIST_GAMEPAD_BACKUP_HELP", "This SLB1 code contains all Shopping List data and settings. Select the field to copy or replace it with a backup code, then choose Restore.")
ZO_CreateStringId("SI_SHOPPING_LIST_GAMEPAD_QUALITY", "Quality")
ZO_CreateStringId("SI_SHOPPING_LIST_GAMEPAD_ARCHIVE_DETAILS", "<<1>> entries · <<2>> spent")
ZO_CreateStringId("SI_SHOPPING_LIST_GAMEPAD_SHARE_HELP", "Select the code field, then use Ctrl+C on the keyboard to copy it.")
ZO_CreateStringId("SI_SHOPPING_LIST_GAMEPAD_IMPORT_HELP", "Select the field, then paste a Shopping List code with Ctrl+V or the on-screen keyboard.")
ZO_CreateStringId("SI_SHOPPING_LIST_GAMEPAD_HELP", "Help & Release Notes")
ZO_CreateStringId("SI_SHOPPING_LIST_GAMEPAD_BULK_HELP", "Paste one item per line, optionally followed by x and a quantity, then choose Add Items.")

ZO_CreateStringId("SI_SHOPPING_LIST_FILTER_ALL", "All items")
ZO_CreateStringId("SI_SHOPPING_LIST_FILTER_NEEDED", "Needed")
ZO_CreateStringId("SI_SHOPPING_LIST_FILTER_COMPLETED", "Completed")
ZO_CreateStringId("SI_SHOPPING_LIST_FILTER_OVER_TARGET", "Over target")
ZO_CreateStringId("SI_SHOPPING_LIST_FILTER_RESTRICTED", "Rule-restricted")
ZO_CreateStringId("SI_SHOPPING_LIST_SETTINGS_ITEM_FILTER", "Item filter")

ZO_CreateStringId("SI_SHOPPING_LIST_BULK_TITLE", "Bulk Add Shopping List Items")
ZO_CreateStringId("SI_SHOPPING_LIST_BULK_HELP", "Paste one item per line. Use Item Name x 10, 10 x Item Name, or Item Name, 10. A line without a quantity adds one.")
ZO_CreateStringId("SI_SHOPPING_LIST_BULK_PLACEHOLDER", "Item Name x 10")
ZO_CreateStringId("SI_SHOPPING_LIST_BULK_ADD", "Add Items")
ZO_CreateStringId("SI_SHOPPING_LIST_BULK_ERROR_LINE", "Line <<1>> does not contain a valid item name and quantity.")
ZO_CreateStringId("SI_SHOPPING_LIST_BULK_ERROR_TOO_MANY", "Bulk entry is limited to <<1>> items at a time.")
ZO_CreateStringId("SI_SHOPPING_LIST_BULK_ERROR_EMPTY", "Paste at least one item to add.")
ZO_CreateStringId("SI_SHOPPING_LIST_BULK_ADDED", "Added <<1>> items to the current list.")

ZO_CreateStringId("SI_SHOPPING_LIST_LIST_NOTE", "List Notes")
ZO_CreateStringId("SI_SHOPPING_LIST_EDITOR_NOTE", "Item Notes")
ZO_CreateStringId("SI_SHOPPING_LIST_NOTE_PLACEHOLDER", "Optional notes")
ZO_CreateStringId("SI_SHOPPING_LIST_NOTE_MARKER", "<<1>> [Note]")
ZO_CreateStringId("SI_SHOPPING_LIST_INVENTORY_PROGRESS", "<<1>>/<<2>> · O:<<3>>")
ZO_CreateStringId("SI_SHOPPING_LIST_INVENTORY_BREAKDOWN", "Owned: <<1>> · Backpack <<2>> · Bank <<3>> · Craft Bag <<4>>")
ZO_CreateStringId("SI_SHOPPING_LIST_ACCESSIBILITY_OVER_TARGET", "[!] Over price target")
ZO_CreateStringId("SI_SHOPPING_LIST_ACCESSIBILITY_ERROR_PREFIX", "[!] <<1>>")
ZO_CreateStringId("SI_SHOPPING_LIST_ACCESSIBILITY_STATUS_PREFIX", "[+] <<1>>")

ZO_CreateStringId("SI_SHOPPING_LIST_TRIP_TITLE", "Active Shopping Lists")
ZO_CreateStringId("SI_SHOPPING_LIST_TRIP_HELP", "Enable merged trips to shop from every checked list at once.\nPurchases never update unchecked lists.")
ZO_CreateStringId("SI_SHOPPING_LIST_TRIP_ALL", "All")
ZO_CreateStringId("SI_SHOPPING_LIST_TRIP_CURRENT_ONLY", "Current Only")
ZO_CreateStringId("SI_SHOPPING_LIST_TRIP_SELECTED_LIST", "<<1>> (selected)")
ZO_CreateStringId("SI_SHOPPING_LIST_TRIP_ENABLE", "Enable Merged Trip")
ZO_CreateStringId("SI_SHOPPING_LIST_TRIP_DISABLE", "Use One List")
ZO_CreateStringId("SI_SHOPPING_LIST_TRIP_SELECTION_UPDATED", "Shopping-trip lists updated.")
ZO_CreateStringId("SI_SHOPPING_LIST_TRIP_ENABLED", "Merged shopping trip enabled.")
ZO_CreateStringId("SI_SHOPPING_LIST_TRIP_DISABLED", "Using only the selected list.")
ZO_CreateStringId("SI_SHOPPING_LIST_TRIP_LIST_ACTIVE", "[x] <<1>>")
ZO_CreateStringId("SI_SHOPPING_LIST_TRIP_LIST_INACTIVE", "[ ] <<1>>")
ZO_CreateStringId("SI_SHOPPING_LIST_TRIP_ITEM_NAME", "<<1>>: <<2>>")

ZO_CreateStringId("SI_SHOPPING_LIST_HELP_TITLE", "Shopping List Help")
ZO_CreateStringId("SI_SHOPPING_LIST_HELP_GETTING_STARTED", "Getting Started")
ZO_CreateStringId("SI_SHOPPING_LIST_HELP_RELEASE_NOTES", "Release Notes")
ZO_CreateStringId("SI_SHOPPING_LIST_HELP_TOOLTIP", "Open help and release notes.")
ZO_CreateStringId("SI_SHOPPING_LIST_HELP_CONTENT", "Shopping List tracks purchases from the guild store currently open. It never searches traders remotely.\n\n1. Create or select a named list.\n2. Enter an item name and quantity, or right-click an item link in chat and add it to the current list.\n3. Use Edit to add an item note, matching rules, or a price target.\n4. Open a guild store and use Find.\n5. Successful purchases update the shopping list automatically.\n\nOwned counts show matching items in your backpack, bank, subscriber bank, and craft bag. These counts are live inventory information and never count as purchases.\n\nManage includes list notes and actions, Bulk Add, Undo, Clear Completed, shopping-trip setup, sharing, and full backup. Bulk Add accepts one item per line with an optional quantity. Undo restores the most recent item, list, or cleared batch.\n\nLightweight SL1 Share/Import codes contain only one list name, item names, and quantities. Full SLB1 backup codes contain every active and archived list, notes, rules, purchase data, and settings; restoring one replaces all current Shopping List data.\n\nUse the filter below the item list to show all, needed, completed, over-price-target, or rule-restricted items. Merged trips combine every checked list in one view while leaving unchecked lists untouched. Budget tracks spending without blocking a purchase.\n\nFont scale, stronger contrast, and non-color-only indicators are available in Add-on Settings.\n\nUse /shoppinglist to toggle the window. Use /shoppinglisthelp to reopen this panel. In gamepad mode, press the right stick for Manage and Help.")
ZO_CreateStringId("SI_SHOPPING_LIST_RELEASE_NOTES_CONTENT", "\n\nCurrent release · 0.16.2\n• Added an option to add linked chat items to the current shopping list from their right-click menu.\n\n0.16.1\n• Restored the Trait, Quality Rule, Quality, and Level Rule dropdowns in the keyboard item editor.\n• Corrected Craft Bag quantities by using ESO's virtual bag slot enumeration.\n\n0.16.0\n• Added live backpack, bank, subscriber bank, and craft bag quantities without changing purchase progress.\n• Added persistent list and item notes.\n• Added complete SLB1 backup and restore codes alongside lightweight SL1 sharing codes.\n• Added font scaling, stronger contrast, and optional non-color-only status indicators.\n\n0.15.4\n• Completed gamepad list management, persistent Undo, bulk entry, item filters, and merged shopping trips.\n• Kept the cursor active after confirmation dialogs and when returning to ESO.\n• Corrected Active Shopping Lists description wrapping.\n\n0.15.2\n• Added an in-game chat warning that names any required libraries that are missing.\n\n0.15.1\n• Lists can now be archived whether they are unfinished, completed, or empty.\n• Corrected the Archive button appearing unresponsive for unfinished lists.\n\n0.15.0\n• Added in-game help and recent release notes for keyboard and gamepad.\n• Added the /shoppinglisthelp command and a ? button in the main window.\n\n0.14.0\n• Added the gamepad Manage menu.\n• Added controller editing for matching rules and price targets.\n• Added controller archive, restore, share, and import workflows.")

ZO_CreateStringId("SI_SHOPPING_LIST_ARCHIVE_TITLE", "Archived Shopping Lists")
ZO_CreateStringId("SI_SHOPPING_LIST_ARCHIVE_EMPTY", "No shopping lists have been archived.")
ZO_CreateStringId("SI_SHOPPING_LIST_ARCHIVE_COLUMN_LIST", "List")
ZO_CreateStringId("SI_SHOPPING_LIST_ARCHIVE_COLUMN_DETAILS", "Archived / Spending")
ZO_CreateStringId("SI_SHOPPING_LIST_STATUS_LIST_RESTORED", "Restored <<1>>.")
ZO_CreateStringId("SI_SHOPPING_LIST_ARCHIVE_SUMMARY", "<<1>> <<2>>")
ZO_CreateStringId("SI_SHOPPING_LIST_ARCHIVE_ROW", "<<1>>  (<<2>> <<3>>)")
ZO_CreateStringId("SI_SHOPPING_LIST_ARCHIVE_DETAILS", "<<1>> · <<2>>")

ZO_CreateStringId("SI_SHOPPING_LIST_HISTORY_TITLE", "Purchase History")
ZO_CreateStringId("SI_SHOPPING_LIST_HISTORY_DATE", "Date")
ZO_CreateStringId("SI_SHOPPING_LIST_HISTORY_QUANTITY", "Qty")
ZO_CreateStringId("SI_SHOPPING_LIST_HISTORY_EACH", "Each")
ZO_CreateStringId("SI_SHOPPING_LIST_HISTORY_TOTAL", "Total")
ZO_CreateStringId("SI_SHOPPING_LIST_HISTORY_SOURCE", "Guild / Seller")
ZO_CreateStringId("SI_SHOPPING_LIST_UNKNOWN_DATE", "Unknown")
ZO_CreateStringId("SI_SHOPPING_LIST_UNKNOWN_TRADER", "Unknown trader")
ZO_CreateStringId("SI_SHOPPING_LIST_HISTORY_SUMMARY", "<<1>> <<2>> · <<3>> total")
ZO_CreateStringId("SI_SHOPPING_LIST_NO_RECORDED_PURCHASES", "No recorded purchases")

ZO_CreateStringId("SI_SHOPPING_LIST_EDITOR_TITLE", "Edit Shopping List Item")
ZO_CreateStringId("SI_SHOPPING_LIST_EDITOR_QUANTITY", "Quantity")
ZO_CreateStringId("SI_SHOPPING_LIST_EDITOR_SET", "Set")
ZO_CreateStringId("SI_SHOPPING_LIST_EDITOR_ANY_SET", "Any set")
ZO_CreateStringId("SI_SHOPPING_LIST_EDITOR_TRAIT", "Trait")
ZO_CreateStringId("SI_SHOPPING_LIST_EDITOR_ANY_TRAIT", "Any trait")
ZO_CreateStringId("SI_SHOPPING_LIST_EDITOR_QUALITY_RULE", "Quality rule")
ZO_CreateStringId("SI_SHOPPING_LIST_EDITOR_LEVEL_RULE", "Level rule")
ZO_CreateStringId("SI_SHOPPING_LIST_EDITOR_LEVEL", "Level")
ZO_CreateStringId("SI_SHOPPING_LIST_EDITOR_CHAMPION_POINTS", "Champion points")
ZO_CreateStringId("SI_SHOPPING_LIST_EDITOR_MAX_UNIT_PRICE", "Maximum unit price")
ZO_CreateStringId("SI_SHOPPING_LIST_EDITOR_GOLD_NONE", "gold (blank = none)")
ZO_CreateStringId("SI_SHOPPING_LIST_EDITOR_HINT", "Any leaves that property unrestricted. Set names must match exactly.")
ZO_CreateStringId("SI_SHOPPING_LIST_CHOICE_ANY", "Any")
ZO_CreateStringId("SI_SHOPPING_LIST_CHOICE_AT_LEAST", "At least")
ZO_CreateStringId("SI_SHOPPING_LIST_CHOICE_EXACTLY", "Exactly")
ZO_CreateStringId("SI_SHOPPING_LIST_NO_PURCHASE_PRICES", "No purchase prices recorded yet.")
ZO_CreateStringId("SI_SHOPPING_LIST_LAST_UNIT_PRICE", "Last <<1>> each")
ZO_CreateStringId("SI_SHOPPING_LIST_OVER_TARGET", "over target")
ZO_CreateStringId("SI_SHOPPING_LIST_PURCHASE_SUMMARY", "<<1>> <<2>> · <<3>> total · <<4>> average\n<<5>>")
ZO_CreateStringId("SI_SHOPPING_LIST_STATUS_ITEM_ORDER_UPDATED", "Item order updated.")
ZO_CreateStringId("SI_SHOPPING_LIST_STATUS_ITEM_UPDATED", "Updated <<1>>.")

ZO_CreateStringId("SI_SHOPPING_LIST_SHARE_ERROR_NO_LIST", "There is no list to share.")
ZO_CreateStringId("SI_SHOPPING_LIST_SHARE_ERROR_LIST_NAME_LONG", "The list name is too long to share.")
ZO_CreateStringId("SI_SHOPPING_LIST_SHARE_ERROR_TOO_MANY_ITEMS", "Lists with more than 500 items cannot be shared.")
ZO_CreateStringId("SI_SHOPPING_LIST_SHARE_ERROR_ITEM_NAME_LONG", "One of the item names is too long to share.")
ZO_CreateStringId("SI_SHOPPING_LIST_SHARE_ERROR_QUANTITY", "Shared item quantities must be between 1 and 1,000,000.")
ZO_CreateStringId("SI_SHOPPING_LIST_SHARE_ERROR_LIST_LONG", "This list is too large for a sharing code.")
ZO_CreateStringId("SI_SHOPPING_LIST_SHARE_ERROR_CODE_LONG", "That sharing code is too long.")
ZO_CreateStringId("SI_SHOPPING_LIST_SHARE_ERROR_PREFIX", "Shopping List codes must begin with <<1>>")
ZO_CreateStringId("SI_SHOPPING_LIST_SHARE_ERROR_INVALID", "That sharing code is not valid.")
ZO_CreateStringId("SI_SHOPPING_LIST_SHARE_ERROR_VERSION", "This sharing code uses an unsupported format.")
ZO_CreateStringId("SI_SHOPPING_LIST_SHARE_ERROR_LIST_DATA", "That sharing code contains invalid list data.")
ZO_CreateStringId("SI_SHOPPING_LIST_SHARE_ERROR_ITEM_DATA", "That sharing code contains invalid item data.")
ZO_CreateStringId("SI_SHOPPING_LIST_SHARE_ERROR_EXTRA_DATA", "That sharing code contains unexpected data.")
ZO_CreateStringId("SI_SHOPPING_LIST_SHARE_TITLE", "Share Shopping List")
ZO_CreateStringId("SI_SHOPPING_LIST_SHARE_HELP", "To share: copy this list's code and send it to another player.\nTo import: choose Import Code and paste the received code.")
ZO_CreateStringId("SI_SHOPPING_LIST_SHARE_CURRENT_CODE", "Current List Code")
ZO_CreateStringId("SI_SHOPPING_LIST_SHARE_SELECT_CODE", "Select Code")
ZO_CreateStringId("SI_SHOPPING_LIST_SHARE_IMPORT_CODE", "Import Code")
ZO_CreateStringId("SI_SHOPPING_LIST_BACKUP_BUTTON", "Backup")
ZO_CreateStringId("SI_SHOPPING_LIST_BACKUP_TITLE", "Full Data Backup and Restore")
ZO_CreateStringId("SI_SHOPPING_LIST_BACKUP_HELP", "Backup codes contain every active and archived list, notes, matching rules, budgets, purchase history, and settings. Restoring replaces all current Shopping List data.")
ZO_CreateStringId("SI_SHOPPING_LIST_BACKUP_PLACEHOLDER", "Paste an SLB1 backup code here")
ZO_CreateStringId("SI_SHOPPING_LIST_BACKUP_GENERATE", "Generate Backup")
ZO_CreateStringId("SI_SHOPPING_LIST_BACKUP_RESTORE", "Restore Code")
ZO_CreateStringId("SI_SHOPPING_LIST_BACKUP_RESTORE_TITLE", "Restore Shopping List Backup")
ZO_CreateStringId("SI_SHOPPING_LIST_BACKUP_RESTORE_CONFIRM", "Replace all current Shopping List data with this backup? This cannot be undone after logging out or reloading the UI.")
ZO_CreateStringId("SI_SHOPPING_LIST_BACKUP_COPY_HINT", "The full backup code is selected. Copy it with Ctrl+C and store it somewhere safe.")
ZO_CreateStringId("SI_SHOPPING_LIST_BACKUP_RESTORED", "Full Shopping List backup restored.")
ZO_CreateStringId("SI_SHOPPING_LIST_BACKUP_ERROR_DATA", "The backup contains invalid Shopping List data.")
ZO_CreateStringId("SI_SHOPPING_LIST_BACKUP_ERROR_LONG", "This backup code is too long.")
ZO_CreateStringId("SI_SHOPPING_LIST_BACKUP_ERROR_PREFIX", "Backup codes must begin with <<1>>.")
ZO_CreateStringId("SI_SHOPPING_LIST_BACKUP_ERROR_INVALID", "This backup code is invalid, incomplete, or damaged.")
ZO_CreateStringId("SI_SHOPPING_LIST_SHARE_COPY_HINT", "Press Ctrl+C to copy the selected code.")
ZO_CreateStringId("SI_SHOPPING_LIST_STATUS_LIST_IMPORTED", "Imported <<1>> with <<2>> <<3>>.")
ZO_CreateStringId("SI_SHOPPING_LIST_IMPORT_TITLE", "Import Shopping List")
ZO_CreateStringId("SI_SHOPPING_LIST_IMPORT_HELP", "Paste a Shopping List sharing code below.")
ZO_CreateStringId("SI_SHOPPING_LIST_IMPORT_PLACEHOLDER", "Paste sharing code")

ZO_CreateStringId("SI_SHOPPING_LIST_SETTINGS_OPEN_WITH_STORE", "Open with guild stores")
ZO_CreateStringId("SI_SHOPPING_LIST_SETTINGS_CLOSE_WITH_STORE", "Close with guild stores")
ZO_CreateStringId("SI_SHOPPING_LIST_SETTINGS_SHOW_COMPLETED", "Show completed items")
ZO_CreateStringId("SI_SHOPPING_LIST_SETTINGS_ANNOUNCE_PURCHASES", "Announce matched purchases")
ZO_CreateStringId("SI_SHOPPING_LIST_SETTINGS_PANEL_SIDE", "Preferred panel side")
ZO_CreateStringId("SI_SHOPPING_LIST_SETTINGS_LEFT", "Left")
ZO_CreateStringId("SI_SHOPPING_LIST_SETTINGS_RIGHT", "Right")
ZO_CreateStringId("SI_SHOPPING_LIST_SETTINGS_RESET_WINDOW", "Reset window position and size")
ZO_CreateStringId("SI_SHOPPING_LIST_SETTINGS_CLEAR_COMPLETED", "Remove completed items from current list")
ZO_CreateStringId("SI_SHOPPING_LIST_SETTINGS_ACCESSIBILITY", "Accessibility")
ZO_CreateStringId("SI_SHOPPING_LIST_SETTINGS_FONT_SCALE", "Font scale")
ZO_CreateStringId("SI_SHOPPING_LIST_SETTINGS_HIGH_CONTRAST", "Stronger contrast")
ZO_CreateStringId("SI_SHOPPING_LIST_SETTINGS_HIGH_CONTRAST_TOOLTIP", "Uses black window backgrounds, brighter borders, and stronger text contrast throughout Shopping List.")
ZO_CreateStringId("SI_SHOPPING_LIST_SETTINGS_NON_COLOR", "Non-color-only status indicators")
ZO_CreateStringId("SI_SHOPPING_LIST_SETTINGS_NON_COLOR_TOOLTIP", "Adds text symbols to success, error, and over-price-target states so they do not rely on color alone.")

ZO_CreateStringId("SI_SHOPPING_LIST_SEARCH_OPEN_STORE", "Open a guild store before searching.")
ZO_CreateStringId("SI_SHOPPING_LIST_SEARCHING_FOR", "Searching for <<1>>.")
ZO_CreateStringId("SI_SHOPPING_LIST_SEARCH_AGS_NOT_READY", "AwesomeGuildStore's search is not ready yet.")
ZO_CreateStringId("SI_SHOPPING_LIST_SEARCH_CHOOSE_AUTOCOMPLETE", "Choose an autocomplete result to make this item searchable.")
ZO_CreateStringId("SI_SHOPPING_LIST_CONTEXT_ADD_TO_LIST", "Add to <<1>>")
ZO_CreateStringId("SI_SHOPPING_LIST_CHAT_OVER_BUDGET", "Shopping List: <<1>> is over budget by <<2>> gold.")
ZO_CreateStringId("SI_SHOPPING_LIST_CHAT_PURCHASE_PROGRESS", "Shopping List: <<1>> <<2>>/<<3>>")
